title: Demo Work 2
summary: 第二个示例作品，用于验证列表与标签聚合。
type: demo
date: 2026-01-02
tags:
  - demo
  - demo2
category: Web App
demo:
  kind: iframe
  src: /demos/gcy/demo2/
  devSrc: http://localhost:5173/
  height: 720
